# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nn_order_sample.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nn_order_sample.proto',
  package='pipeline',
  syntax='proto2',
  serialized_options=_b('\n\'com.xxchuxing.rprank.fe.jobs.pipelineB\023NNOrderSampleProtos'),
  serialized_pb=_b('\n\x15nn_order_sample.proto\x12\x08pipeline\"\xcf\x03\n\rNNOrderSample\x12\x0b\n\x03qid\x18\x01 \x02(\t\x12\x0b\n\x03pid\x18\x02 \x02(\x04\x12\x0b\n\x03\x64id\x18\x03 \x02(\x04\x12\x0f\n\x07od_grid\x18\x04 \x03(\x04\x12\x0f\n\x07od_dist\x18\x05 \x03(\x01\x12\x11\n\ttimestamp\x18\x06 \x02(\x04\x12\x35\n\tpos_feats\x18\x07 \x03(\x0b\x32\".pipeline.NNOrderSample.ArrayFeats\x12\x35\n\tneg_feats\x18\x08 \x03(\x0b\x32\".pipeline.NNOrderSample.ArrayFeats\x12\x37\n\x0bothers_type\x18\t \x03(\x0b\x32\".pipeline.NNOrderSample.OthersType\x12\x0e\n\x06\x63ityid\x18\n \x01(\r\x1a\x80\x01\n\nArrayFeats\x12\x13\n\x0bnumeric_val\x18\x01 \x03(\x01\x12\x11\n\tlink_list\x18\x02 \x03(\x04\x12\x11\n\txgb_preds\x18\x03 \x03(\r\x12\x37\n\x0bothers_feat\x18\x04 \x03(\x0b\x32\".pipeline.NNOrderSample.OthersType\x1a(\n\nOthersType\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\"<\n\x10NNOrderSampleSet\x12(\n\x07samples\x18\x01 \x03(\x0b\x32\x17.pipeline.NNOrderSampleB>\n\'com.xxchuxing.rprank.fe.jobs.pipelineB\x13NNOrderSampleProtos')
)




_NNORDERSAMPLE_ARRAYFEATS = _descriptor.Descriptor(
  name='ArrayFeats',
  full_name='pipeline.NNOrderSample.ArrayFeats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='numeric_val', full_name='pipeline.NNOrderSample.ArrayFeats.numeric_val', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='link_list', full_name='pipeline.NNOrderSample.ArrayFeats.link_list', index=1,
      number=2, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='xgb_preds', full_name='pipeline.NNOrderSample.ArrayFeats.xgb_preds', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='others_feat', full_name='pipeline.NNOrderSample.ArrayFeats.others_feat', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=329,
  serialized_end=457,
)

_NNORDERSAMPLE_OTHERSTYPE = _descriptor.Descriptor(
  name='OthersType',
  full_name='pipeline.NNOrderSample.OthersType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='pipeline.NNOrderSample.OthersType.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='pipeline.NNOrderSample.OthersType.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=459,
  serialized_end=499,
)

_NNORDERSAMPLE = _descriptor.Descriptor(
  name='NNOrderSample',
  full_name='pipeline.NNOrderSample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='qid', full_name='pipeline.NNOrderSample.qid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pid', full_name='pipeline.NNOrderSample.pid', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='did', full_name='pipeline.NNOrderSample.did', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='od_grid', full_name='pipeline.NNOrderSample.od_grid', index=3,
      number=4, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='od_dist', full_name='pipeline.NNOrderSample.od_dist', index=4,
      number=5, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='pipeline.NNOrderSample.timestamp', index=5,
      number=6, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos_feats', full_name='pipeline.NNOrderSample.pos_feats', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='neg_feats', full_name='pipeline.NNOrderSample.neg_feats', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='others_type', full_name='pipeline.NNOrderSample.others_type', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cityid', full_name='pipeline.NNOrderSample.cityid', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_NNORDERSAMPLE_ARRAYFEATS, _NNORDERSAMPLE_OTHERSTYPE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=499,
)


_NNORDERSAMPLESET = _descriptor.Descriptor(
  name='NNOrderSampleSet',
  full_name='pipeline.NNOrderSampleSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='samples', full_name='pipeline.NNOrderSampleSet.samples', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=501,
  serialized_end=561,
)

_NNORDERSAMPLE_ARRAYFEATS.fields_by_name['others_feat'].message_type = _NNORDERSAMPLE_OTHERSTYPE
_NNORDERSAMPLE_ARRAYFEATS.containing_type = _NNORDERSAMPLE
_NNORDERSAMPLE_OTHERSTYPE.containing_type = _NNORDERSAMPLE
_NNORDERSAMPLE.fields_by_name['pos_feats'].message_type = _NNORDERSAMPLE_ARRAYFEATS
_NNORDERSAMPLE.fields_by_name['neg_feats'].message_type = _NNORDERSAMPLE_ARRAYFEATS
_NNORDERSAMPLE.fields_by_name['others_type'].message_type = _NNORDERSAMPLE_OTHERSTYPE
_NNORDERSAMPLESET.fields_by_name['samples'].message_type = _NNORDERSAMPLE
DESCRIPTOR.message_types_by_name['NNOrderSample'] = _NNORDERSAMPLE
DESCRIPTOR.message_types_by_name['NNOrderSampleSet'] = _NNORDERSAMPLESET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NNOrderSample = _reflection.GeneratedProtocolMessageType('NNOrderSample', (_message.Message,), dict(

  ArrayFeats = _reflection.GeneratedProtocolMessageType('ArrayFeats', (_message.Message,), dict(
    DESCRIPTOR = _NNORDERSAMPLE_ARRAYFEATS,
    __module__ = 'nn_order_sample_pb2'
    # @@protoc_insertion_point(class_scope:pipeline.NNOrderSample.ArrayFeats)
    ))
  ,

  OthersType = _reflection.GeneratedProtocolMessageType('OthersType', (_message.Message,), dict(
    DESCRIPTOR = _NNORDERSAMPLE_OTHERSTYPE,
    __module__ = 'nn_order_sample_pb2'
    # @@protoc_insertion_point(class_scope:pipeline.NNOrderSample.OthersType)
    ))
  ,
  DESCRIPTOR = _NNORDERSAMPLE,
  __module__ = 'nn_order_sample_pb2'
  # @@protoc_insertion_point(class_scope:pipeline.NNOrderSample)
  ))
_sym_db.RegisterMessage(NNOrderSample)
_sym_db.RegisterMessage(NNOrderSample.ArrayFeats)
_sym_db.RegisterMessage(NNOrderSample.OthersType)

NNOrderSampleSet = _reflection.GeneratedProtocolMessageType('NNOrderSampleSet', (_message.Message,), dict(
  DESCRIPTOR = _NNORDERSAMPLESET,
  __module__ = 'nn_order_sample_pb2'
  # @@protoc_insertion_point(class_scope:pipeline.NNOrderSampleSet)
  ))
_sym_db.RegisterMessage(NNOrderSampleSet)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
